version: '3'
services:
  #Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  #Kafka broker
  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "49999:49999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_JMX_PORT: 49999
      KAFKA_MESSAGE_MAX_BYTES: 10000
#      KAFKA_MIN_INSYNC_REPLICAS: 2
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 2

  #Redpanda console (kafka visualization toll)
  redpanda-console:
    image: docker.redpanda.com/vectorized/console:v2.2.0
    container_name: redpanda-console
    ports:
      - "7070:8080"
    environment:
      KAFKA_BROKERS: broker:29092
#      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
#      KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081"
    depends_on:
      - broker
    restart: on-failure

  #Prometheus
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  #Grafana dashboard
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  stock-quote-producer:
    build:
      dockerfile: ./infra/docker/Dockerfile
      context: "../../"
    container_name: stock-quote-producer
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: broker:29092
    restart: on-failure
    depends_on:
      - broker
      - prometheus
