global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 35s
    scrape_timeout: 30s
    static_configs:
      - targets: ['stock-quote-producer:8080']
    basic_auth:
      username: 'admin'
      password: 'admin'
